#apiVersion: v1
#kind: Namespace
#metadata:
#  name: vick-system
#---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: vick-system
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db
  namespace: vick-system
data:
  mysql-database: VICK_TELEMETRY_SUMMARY_DB
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: vick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db
              key: mysql-database
        - name: MYSQL_ROOT_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: vick-wso2sp-worker
  namespace: vick-system
spec:
  type: NodePort
  ports:
  - port: 9091
    name: http2
    protocol: TCP
  selector:
    app: vick-wso2sp-worker
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vick-wso2sp-worker
  namespace: vick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vick-wso2sp-worker
    spec:
      containers:
      - name: vick-wso2sp-worker
        image: "docker.io/vick-wso2sp-worker:4.3.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9091
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myssqlervice; sleep 30; done;']
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: vick-wso2sp-dashboard-service
#  namespace: vick-system
#spec:
#  type: NodePort
#  ports:
#  - port: 9714
#    name: binary-ssl
#    protocol: TCP
#    targetPort: 9714
#  - port: 9643
#    name: portal
#    protocol: TCP
#    targetPort: 9643
#  - port: 9614
#    name: binary-tcp
#    protocol: TCP
#    targetPort: 9614
#  - port: 7713
#    name: thrift-ssl
#    protocol: TCP
#    targetPort: 7713
#  - port: 7613
#    name: thrift-tcp
#    protocol: TCP
#    targetPort: 7613
#  selector:
#    app: vick-wso2sp-dashoard
apiVersion: v1
kind: Service
metadata:
  name: vick-wso2sp-dashboard-service
  namespace: vick-system
spec:
  type: NodePort
  ports:
  - port: 9643
    name: http
    protocol: TCP
  selector:
    app: vick-wso2sp-dashoard
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vick-wso2sp-dashboard
  namespace: vick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vick-wso2sp-dashboard
    spec:
      containers:
      - name: vick-wso2sp-dashboard
        image: "docker.io/vick-wso2sp-dashboard:4.3.0"
        imagePullPolicy: IfNotPresent
        ports:
#        - containerPort: 9714
        - containerPort: 9643
#        - containerPort: 9614
#        - containerPort: 7713
#        - containerPort: 7613
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myssqlervice; sleep 30; done;']