#apiVersion: v1
#kind: Namespace
#metadata:
#  name: vick-system
#---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-conf
  namespace: vick-system
data:
  init-wso2sp-db.sql: |
    CREATE USER 'wso2carbon'@'%' IDENTIFIED BY 'wso2carbon';

    CREATE DATABASE SP_WORKER_STATE_DB;
    USE SP_WORKER_STATE_DB;
    GRANT ALL ON SP_WORKER_STATE_DB.* TO 'wso2carbon'@'%' identified by 'wso2carbon';

    CREATE DATABASE SP_DASHBOARD_STATE_DB;
    USE SP_DASHBOARD_STATE_DB;
    GRANT ALL ON SP_DASHBOARD_STATE_DB.* TO 'wso2carbon'@'%' identified by 'wso2carbon';

    CREATE DATABASE MESSAGE_TRACING_DB;
    USE MESSAGE_TRACING_DB;
    GRANT ALL ON MESSAGE_TRACING_DB.* TO 'wso2carbon'@'%' identified by 'wso2carbon';

    CREATE DATABASE WSO2_METRICS_DB;
    USE WSO2_METRICS_DB;
    GRANT ALL ON WSO2_METRICS_DB.* TO 'wso2carbon'@'%' identified by 'wso2carbon';

    CREATE DATABASE WSO2_STATUS_DASHBOARD_DB;
    USE WSO2_STATUS_DASHBOARD_DB;
    GRANT ALL ON WSO2_STATUS_DASHBOARD_DB.* TO 'wso2carbon'@'%' identified by 'wso2carbon';

    CREATE DATABASE WSO2AM_MGW_ANALYTICS_DB;
    USE WSO2AM_MGW_ANALYTICS_DB;
    GRANT ALL ON WSO2AM_MGW_ANALYTICS_DB.* TO 'wso2carbon'@'%' identified by 'wso2carbon';

    CREATE DATABASE VICK_TELEMETRY_SUMMARY_DB;
    USE VICK_TELEMETRY_SUMMARY_DB;
    GRANT ALL ON VICK_TELEMETRY_SUMMARY_DB.* TO 'wso2carbon'@'%' identified by 'wso2carbon';
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: vick-system
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: vick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        volumeMounts:
        # - name: mysql-persistent-storage
        # mountPath: /var/lib/mysql
        - name: wso2sp-mysql-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        # - name: mysql-persistent-storage
        # persistentVolumeClaim:
        # claimName: mysql-pv-claim
      - name: wso2sp-mysql-init
        configMap:
          name: mysql-init-conf

---
apiVersion: v1
kind: Service
metadata:
  name: vick-wso2sp-worker
  namespace: vick-system
spec:
  type: NodePort
  ports:
  - port: 9091
    name: http2
    protocol: TCP
  - port: 9411
    name: zipkin
    protocol: TCP
  selector:
    app: vick-wso2sp-worker
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vick-wso2sp-worker
  namespace: vick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vick-wso2sp-worker
    spec:
      containers:
      - name: vick-wso2sp-worker
        image: "vick-wso2sp-worker:4.3.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9091
        - containerPort: 9411
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myssqlervice; sleep 30; done;']
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: vick-wso2sp-dashboard-service
#  namespace: vick-system
#spec:
#  type: NodePort
#  ports:
#  - port: 9714
#    name: binary-ssl
#    protocol: TCP
#    targetPort: 9714
#  - port: 9643
#    name: portal
#    protocol: TCP
#    targetPort: 9643
#  - port: 9614
#    name: binary-tcp
#    protocol: TCP
#    targetPort: 9614
#  - port: 7713
#    name: thrift-ssl
#    protocol: TCP
#    targetPort: 7713
#  - port: 7613
#    name: thrift-tcp
#    protocol: TCP
#    targetPort: 7613
#  selector:
#    app: vick-wso2sp-dashoard
apiVersion: v1
kind: Service
metadata:
  name: vick-wso2sp-dashboard-service
  namespace: vick-system
spec:
  type: NodePort
  ports:
  - port: 9643
    name: http
    protocol: TCP
  selector:
    app: vick-wso2sp-dashoard
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vick-wso2sp-dashboard
  namespace: vick-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vick-wso2sp-dashboard
    spec:
      containers:
      - name: vick-wso2sp-dashboard
        image: "vick-wso2sp-dashboard:4.3.0"
        imagePullPolicy: IfNotPresent
        ports:
#        - containerPort: 9714
        - containerPort: 9643
#        - containerPort: 9614
#        - containerPort: 7713
#        - containerPort: 7613
      initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myssqlervice; sleep 30; done;']